#!/usr/bin/env python3
"""Turn data files into a C blob table so a WASI binary can serve them from
memory. terminalOS runs WebAssembly through wasm3, whose only preopened
directory is the shell's working directory, so a program cannot open its own
data files from an install prefix. Embedding sidesteps the problem and keeps a
package to a single self-contained .wasm file."""
import sys, os

def main(argv):
    if len(argv) < 3:
        sys.exit("usage: embed.py OUT.c FILE [FILE...]")
    out, files = argv[1], argv[2:]
    with open(out, "w") as c:
        c.write('/* Generated by tools/embed.py. Do not edit. */\n')
        c.write('#include "wasi_embed.h"\n#include <string.h>\n\n')
        names = []
        for i, path in enumerate(files):
            blob = open(path, "rb").read()
            sym = "blob_%d" % i
            names.append((os.path.basename(path), sym, len(blob)))
            c.write("static const unsigned char %s[] = {\n" % sym)
            for off in range(0, len(blob), 20):
                c.write("".join("0x%02x," % b for b in blob[off:off+20]) + "\n")
            c.write("};\n\n")
        c.write("static const embedded_file table[] = {\n")
        for name, sym, size in names:
            c.write('  { "%s", %s, %d },\n' % (name, sym, size))
        c.write("  { 0, 0, 0 }\n};\n\n")
        c.write("""const embedded_file *embedded_lookup(const char *path)
{
  const char *base = strrchr(path, '/');
  const embedded_file *f;

  base = base ? base + 1 : path;
  for (f = table; f->name; f++)
    if (strcmp(f->name, base) == 0)
      return f;
  return 0;
}
""")
    sys.stderr.write("embed.py: wrote %s (%d files, %d bytes)\n"
                     % (out, len(names), sum(n[2] for n in names)))

if __name__ == "__main__":
    main(sys.argv)
